### PR TITLE
Added build for Windows.

### PR DESCRIPTION
**Pull request by alexandr-san4ez**
Build for Windows(32/64) [here](https://github.com/alexandr-san4ez/devdocs-app/releases/download/v0.0.3/devdocs-windows-0.0.3_ia32_x64.7z).

### CODE REVIEW

**Comment by egoist** [comment]
Hi, thanks for the PR, I've changed it to build with `electron-builder`, can you help publishing a windows release? I can add you to the repo :) Hopefully `yarn dist` would work.

**Comment by alexandr-san4ez** [comment]
Built for Windows.
Added installer and unpacked version.

Links: [Win_ia32](https://drive.google.com/uc?id=0B6OZFhZtBgUbR2VBeEZmR2lOd00&export=download), [Win_x64](https://drive.google.com/uc?id=0B6OZFhZtBgUbeFdaSktqVkNkZ3c&export=download)

**Comment by egoist** [comment]
I've added you to the Collaborators, you can edit the [release](https://github.com/egoist/devdocs-app/releases/tag/v0.1.0) directly

**Comment by alexandr-san4ez** [comment]
Updated.

**Comment by egoist** [comment]
I guess you only need to zip the .exe file

**Comment by egoist** [comment]
btw, we don't need x64 build, the ia32 works on 64bit platform.

it looks we can directly upload .exe file to github release, so you don't need it zip it

**Comment by alexandr-san4ez** [comment]
I thought it would not be amiss. (x64)

**Comment by egoist** [comment]
thanks, looks good ;)

**Pull request closed without merging**
