### PR TITLE
Minor project build refactoring

### PR DESCRIPTION
**Pull request by Meadowcottage**
Updated some things that needed updating:
 - Updated dependencies
 - Added background for mac `.dmg` files.
 - Switched to using new NSIS installer for Windows.

Let me know if you wanna push this ahead or change anything back 😄

### CODE REVIEW

**Comment by egoist** [comment]
Hmm, you should update `yarn.lock` too

**Comment by egoist** [comment]
this background looks very confusing to me (two same icons) 😂

**Comment by Meadowcottage** [comment]
Yeah could probs make it a bit clearer whats the app and what's the background. Will change that now. 😄
Also, the fix for the app category. Will moving that to mac not cause issues for building linux dist?

**Comment by Meadowcottage** [comment]
Background assets should make it a but clearer now what is the title and what is the app 😄

**Comment by egoist** [comment]
it seems `category` is no longer a top-level property but platform-specific, we need to add it to `linux` too.

**Pull request merged**
